ARG fedora_version=33

FROM fedora:${fedora_version}

RUN dnf install -y \
        python3 python3-pip python3-setuptools git rpm-build

ADD docker-assets/* /assets/

# Volume used to send distribution archives to host
VOLUME /dist/

ENTRYPOINT ["/bin/bash"]
CMD ["/assets/entrypoint.sh", "rpm"]