theme: jekyll-theme-cayman
title: Unisul Digital
show_downloads: true
github:
  zip_url: https://github.com/yanmarques/software-engineering-work/releases/download/v0.1.0-dev.3/unisul-sync-gui_0.1.0-dev.3.zip